#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Inject new cards + window into index.html & sport.html, then normalize via generators."""
import re
import subprocess
import sys

MAIN = r"C:\Users\DianAgusHermawan\OneDrive - PLN\Hermes\main"

# ---------- load generated sections ----------
tech_sec = open(MAIN + r"\tech_sections.html", encoding="utf-8").read()
sport_sec = open(MAIN + r"\sport_sections.html", encoding="utf-8").read()
tech_sections, tech_slicers = tech_sec.split("\n\n<!-- SLICERS -->\n\n")
sport_sections, sport_slicers = sport_sec.split("\n\n<!-- SLICERS -->\n\n")

WINDOW_STRONG = "14 Agu 11:00 → 18 Agu 2026 11:00 WIB"
WINDUR = "96 jam"
TITLE_DATE = "18 Agu 2026 11:00 WIB"

# ================= INDEX.HTML =================
idx_path = MAIN + r"\index.html"
html = open(idx_path, encoding="utf-8").read()

# 1. title / og / twitter dates
html = html.replace("Tech News Digest — 12 Agu 2026 11:00 WIB", "Tech News Digest — 18 Agu 2026 11:00 WIB")

# 2. window
html = re.sub(
    r'<div class="window">Jendela berita <strong>.*?</strong> · <span id="win-dur">.*?</span> terakhir</div>',
    f'<div class="window">Jendela berita <strong>{WINDOW_STRONG}</strong> · <span id="win-dur">{WINDUR}</span> terakhir</div>',
    html, count=1)

# 3. lead story (Stripe-OpenRouter, AI)
lead_html = '''  <!-- LEAD STORY -->
  <div class="lead" data-cat="ai">
    <div class="tag-row"><span class="tag">Stripe</span></div>
    <h2>Stripe Dikabarkan Akuisisi OpenRouter Lebih dari US$ 7 Miliar — Validasi Lapisan Routing AI</h2>
    <p>Bloomberg melaporkan Stripe menuntaskan kesepakatan mengakuisisi OpenRouter, gerbang akses ratusan model AI, dengan nilai lebih dari US$ 7 miliar — lompatan besar dari valuasi US$ 1,3 miliar pada Mei lalu. Kesepakatan ini memvalidasi model routing AI sebagai lapisan infrastruktur penting di tengah ledakan aplikasi agentic.</p>
    <div class="meta">
      <span class="src">16 Agu · TechCrunch</span>
      <span class="sent up">Kabar positif</span>
      <a class="read-more" href="https://techcrunch.com/2026/08/16/stripe-will-reportedly-acquire-ai-gateway-startup-openrouter-for-7b/" target="_blank" rel="noopener">Baca selengkapnya</a>
    </div>
  </div>
'''
html = re.sub(r'  <!-- LEAD STORY -->.*?</div>\n\n\n  <!-- MARKET TICKERS -->',
              lead_html + "\n\n  <!-- MARKET TICKERS -->", html, count=1, flags=re.S)

# 4. top5 — first 5 grid cards
top5_items = [
    ("#card-1", "Pendapatan Tahunan Anthropic Melonjak ke US$ 65 Miliar", "AI"),
    ("#card-2", "Apple Latih Model AI Khusus untuk China dengan Bantuan Alibaba", "AI"),
    ("#card-3", "Nvidia Nyaris Jamin US$ 100 Miliar Kredit untuk Pusat Data OpenAI", "AI"),
    ("#card-4", "Anthropic Raih Laba Operasional Pertama di Kuartal II 2026", "Earnings"),
    ("#card-5", "Applied Materials Cetak Pendapatan US$ 9,12 Miliar, Ekspansi Kapasitas 2x", "Earnings"),
]
lis = "\n".join(f'      <li><a href="{a}">{t}</a><span class="cat-tag">{c}</span></li>' for a, t, c in top5_items)
top5_html = f'''  <!-- TOP 5 -->
  <div class="top5">
    <h3>Sorotan Hari Ini</h3>
    <ol>
{lis}
    </ol>
  </div>
'''
html = re.sub(r'  <!-- TOP 5 -->.*?\n\n  <!-- LEAD STORY -->', top5_html + "\n  <!-- LEAD STORY -->", html, count=1, flags=re.S)

# 5. slicers (counts)
html = re.sub(r'  <div class="slicers-row sticky" id="categorySlicers".*?</div>\n\n  <div id="news-container">',
              '  <div class="slicers-row sticky" id="categorySlicers" role="group" aria-label="Filter kategori berita">\n' +
              tech_slicers + '\n  </div>\n\n  <div id="news-container">', html, count=1, flags=re.S)

# 6. news-container sections
html = re.sub(r'  <div id="news-container">.*?\n  </div>\n\n  <footer>',
              '  <div id="news-container">\n' + tech_sections + '\n  </div>\n\n  <footer>', html, count=1, flags=re.S)

open(idx_path, "w", encoding="utf-8").write(html)
print("index.html injected")

# ================= SPORT.HTML =================
spt_path = MAIN + r"\sport.html"
shtml = open(spt_path, encoding="utf-8").read()

# news-container sections (slicers regenerated by apply_sport_page)
shtml = re.sub(r'  <div id="news-container">.*?\n  </div>\n\n  <footer>',
               '  <div id="news-container">\n' + sport_sections + '\n  </div>\n\n  <footer>', shtml, count=1, flags=re.S)

open(spt_path, "w", encoding="utf-8").write(shtml)
print("sport.html injected")
